name: Build AppImage

run-name: building appimage
on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: build appimage
      run: /bin/sh ./build_prefixer_appimage.sh
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: AppImage
        path: /dist

  release:
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: AppImage
          merge-multiple: true
      - name: Release AppImage
        uses: pkgforge-dev/make-stable-appimage-release@4ed3d48ccb065352b6e6c0db6d39885b201c54a0 #v1.1
